### ISSUE TITLE
Question: Is it possible to use motion-xray with ProMotion? 

### ISSUE THREAD

**Issue by matthewsinclair** [colinta/motion-xray#8]
@colinta Is it possible to use motion-xray with ProMotion? /cc @jamonholmgren

**Comment by matthewsinclair** [comment]
After a quick browse thru the PM source code, I noticed that `PM::Delegate` will attempt to return an XRay `UIWindow` if it sees that xray is defined. However, if I stick something like `module PM::Xray; end` in my app delegate, then I get the dreaded `uninitialized constant PM (NameError)` error. 

Am I doing something wrong?

**Comment by matthewsinclair** [comment]
Ok, ignore me. I wasn't `require`-ing the `motion-xray` stuff. Xray is starting up, however, now I'm getting another error:

```
(main)> 2015-02-03 23:12:54.041 T-UIKit[16013:3594725] Motion::Xray::XrayWindow(#1189783c0, [[0.0, 0.0], [320.0, 568.0]])
2015-02-03 23:12:54.242 T-UIKit[16013:3594725] xray_ui.rb:434:in `edit:': uninitialized constant SugarCube::Adjust (NameError)
	from xray_ui.rb:249:in `fire_up'
	from xray_ui.rb:47:in `toggle'
	from xray.rb:25:in `toggle'
	from xray_window.rb:7:in `motionEnded:withEvent:'
2015-02-03 23:12:54.252 T-UIKit[16013:3594725] *** Terminating app due to uncaught exception 'NameError', reason: 'xray_ui.rb:434:in `edit:': uninitialized constant SugarCube::Adjust (NameError)
	from xray_ui.rb:249:in `fire_up'
	from xray_ui.rb:47:in `toggle'
	from xray.rb:25:in `toggle'
	from xray_window.rb:7:in `motionEnded:withEvent:'
```

Is `motion-xray` compatible with 2.x of `ProMotion`?

**Comment by colinta** [comment]
Yeah Xray needs some love.  During the last couple months at Jukely we tried to resurrect the project with a slick new design, but I didn't get very far.  And I've been doing objc & swift since august, so I have limited time to maintain the rubymotion gems.

**Comment by matthewsinclair** [comment]
@colinta Ok, thanks. I'll try and see if I can get `rmq` to work. Cheers.
